version: 2
registries:
  artifactory: # Define access for a private registry 
    type: docker-registry
    url: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com
    username: jiaming.hu@ibm.com
    password: ${{secrets.ARTIFACTORY_PASSWORD}}

updates:
  - package-ecosystem: docker
    directory: "/"
    registries:
      - artifactory # Allow version updates for dependencies in this registry
    schedule:
      interval: daily