# permissions for end users to edit deprapiscans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deprapiscan-editor-role
rules:
- apiGroups:
  - operator.horis233.com
  resources:
  - deprapiscans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.horis233.com
  resources:
  - deprapiscans/status
  verbs:
  - get
