# permissions for end users to view depremons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: depremon-viewer-role
rules:
- apiGroups:
  - operator.horis233.com
  resources:
  - depremons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.horis233.com
  resources:
  - depremons/status
  verbs:
  - get
